# Welcome to Jekyll!

# Website settings
title: "HermesNoWorry"
description: "Herme's app to notify the people you trust when something isn't right"
keywords: "Hermes,HermesNoWorry,Mobile,Wearables,github,gh-pages"

baseurl: "/"
url: "http://www.jack003.com"
# url: "http://127.0.0.1:4000"

# author
author:
  name: ''
  first_name: 'Hermes'
  last_name: 'No Worry'
  email: 'dev@hermesnoworry.com'
  facebook_username: 'hermesnoworry'
  github_username: 'hermeshelp'
  head_img: 'static/img/landing/Jack.jpg'

# social link
johnny:
  first_name: 'Johnny'
  last_name: 'Skandalakis'
  description: 'Dev'
  link: 'skandalakis.net'
  email: 'john@skandalakis.net'
  
# social link
tito:
  first_name: 'Tito'
  last_name: 'Nieves'
  description: 'Dev'
  link: '/'
  email: 'hnieves3@gatech.edu'
  
# social link
ankita:
  first_name: 'Ankita'
  last_name: 'Lamba'
  description: 'Dev'
  link: '/'
  email: 'alamba3@gatech.edu'

# landing page
landing:
  home: 'Home'
  about: 'About'
  career: 'Timeline'
  skills: 'Features'
  projects: 'temp'
  blog: 'Blog'
  contact: 'Link'
  
timeline:
 - time-item: first code demo!
   description: We are proud to have launched out first demo. People love the idea and are impressed by the functionality!
   date: Fall 2015
   green: Android
 - time-item: CIC, Georgia Institute of Technology
   description: We won second place in the CIC out of 36 teams! this is proof that people like our app!
   date: Spring 2016
   green: Android
 - time-item: New Android Features!
   description: The app now monitors movement after an incident and cancels the notification process if the user is moving. This greatly reduces false positives!
   date: Summer 2016
   green: Android
 - time-item: iOS Version Under Way!
   description: We are working hard at getting the iOS version up and running so we can annouce our MVP.
   date: Summer 2016
   green: iOS
   
# my projects
project:
  saplatform:
    name: 'Saplatform'
    url: '/Jack614/saplatform'
    img: 'static/img/landing/saplatform.jpg'
  jalpc:
    name: 'Jalpc'
    url: '/Jack614/jalpc_jekyll_theme'
    img: 'static/img/landing/jekyll.jpg'
  angularjs:
    name: 'Jalpc-A'
    url: '/Jack614/Jalpc-A'
    img: 'static/img/landing/angularjs.jpg'

# blog index
index:
  home: 'Home'
  python: 'Python'
  linux: 'Linux'
  html: 'HTML'
  database: 'Database'
  mac: 'Mac'
  life: 'Life'

# donate
donate:
  wechat: 'static/img/pay/wechat.png'
  alipay: 'static/img/pay/alipay.png'

# comment
changyan:
  # appid: cysfY7ULn
  # conf: prod_861928934cecb7a18e15bedaed9dae29
disqus:
  name: jalpc
  public_key: tj2MPaNlHMONwTH5bGDNSXyaBpW7q282MeUzh5CwcjJerNhK8Kxk3aWo7IckzTX7

# share
bshare:
  uuid: 513f778e-a8f7-4c20-9ec2-d29cc2328d75

# baidu analytics
ba:
  uuid: 317acca9ef9255b934e46371e471431d

# google analytics
ga:
  id: UA-73784599-1

# blog img path
img_path: '/static/img/blog'

# Build settings
encoding: "utf-8"

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
